### ISSUE TITLE
Randomization

### ISSUE THREAD

**Issue by PixieStick314** [PixieStick314/P4-comp#29]
Implement a custom intra-language random function, following the requirements set in chapter 3.

**Comment by LokeSGJ** [comment]
Nice that you got it working. In most languages, including Python, seed is a global rule rather than part of the random function (there aren't many cases where you want to generate a bunch of variables from different seeds right after each other). I think our seed rule should be set once, then use that seed for every random call in the scope. The easiest way would be to add a seed field to the Environment class and check if a seed has been set when random is called, else use a random seed.
